### ISSUE TITLE
Release: coordination of recent `A11y` and element tree changes/proposal

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/react-native-testing-library#1164]
Recently we have a lot of activity related to accessibility as well as composite/host elements handling. All of these propositions seem to move RNTL into right direction due to more expressive queries (`*ByRole`), better matching accessibility behaviour of RN/iOS/Android, and increasing compatibility with RTL/DTL. However, the number of changes is getting high, some of which might be breaking changes as well, so we should do some planning in terms of minor/major releases.

My initial proposal is as follows:

## Next minor or patch releases (v11.x.y) - non breaking changes
- [ ] #1161 (issue #1134 ) support `states` in `*ByRole` queries
- [ ] #1064 (issue #970) with `hidden: true`, i.e. having same default behaviour as current queries (resolves #970)
- [ ] #1166 (issue #1165) bug: *ByA11yState query ignores default state values of false

## Next major release (v12.0.0)
- [ ] #1064 switching `hidden: false` to match default DTL/RTL default
- [ ] #1163 ignore `accessible={true}` children when `hidden: false`, potentially fixes #1152
- [ ] #1132 `*ByText` and `*ByDisplayValue`, `*ByPlaceholder` to return host components instead of exported composite `Text`, `TextInput`
- [ ] #1130 default roles for some elements based on observed RN/iOS/Android behaviour

Other PRs in the pipeline are not related to a11y/element tree and do not introduce breaking changes, so we might merge them at any moment, perhaps for minor release if they are production ready. I did not include them here to reduce complexity of the discussion.

@thymikee @AugustinLF @pierrezimmermannbam does that above plan for upcoming releases seems reasonable for you, would you want to include some more features/fixes or exclude anything mentioned above. Looking forward for your feedback.

**Comment by AugustinLF** [comment]
We've also had two valuable PR things [merged since last release](https://github.com/callstack/react-native-testing-library/compare/v11.2.0...main):
- `configure()` in #1141
- fix to text in `QueryByRole` #1141

Overall, I'm a proponent of releasing minor/patches as often as needed (as long as the release process is not too much of a burden). So I don't feel very strongly on bundling PRs together. For instance, if we get #1130 done before any breaking change, I'd suggest to release it!

**Comment by mdjastrzebski** [comment]
@AugustinLF I agree on releasing minor/patches more frequently, so I've updated the original description to make that clear. What was my intention is to band breaking changes with common a11y/element tree theme into one single major release, instead of triggering a higher number of major releases.

**Comment by mdjastrzebski** [comment]
Closing as no longer relevant
