### ISSUE TITLE
Roadmap to 2.0

### ISSUE THREAD

**Issue by Esemesek** [callstack/react-native-testing-library#158]
# Roadmap to `v2.0`:

- [x] - Add `UNSAFE_` prefix to `byProp`, `byType` and `byName` queries (#261)
- [x] - Deprecate (then remove) `shallow`, provide migration path (#264)
- [x] - Add Accessibility (`ByA11yStates`, `ByA11yLabel`, `ByA11yRole`, `ByA11yHint`, `ByA11yState`, `ByA11yValue`) queries (#178, #260, #262)
- [x] - Add `ByDisplayValue` queries (#190)
- [x] - Fix `getByTestId` to only look for `testID` in host components like View or Text, like `getAllByTestId` does already (#270) 
- [x] - enable `cleanup` by default (#238)
- [x] - write migration guide
- [x] - write blog post
- [x] - remove "debug" export from library index (#317) 
- [x] - Unify `waitForElement` to Testing Library signature, rename to `waitFor` (#318)

**Comment by oshimayoan** [comment]
What about `byDisplayValue` for TextInput?

**Comment by thymikee** [comment]
Sure we can add that

**Comment by betoharres** [comment]
Will we have support to async `act`? https://github.com/testing-library/react-testing-library/releases/tag/v6.1.0
I'm getting the same console errors they were trying to fix on that realease.

Thanks for the hard work on the library ❤

**Comment by ellipticaldoor** [comment]
Yes, will be really nice to have async act

**Comment by betoharres** [comment]
@ellipticaldoor 
`Just by updating react-test-renderer we should have the update right?`
No, because it's not in the library `package.json`.
As the README says, it's heavily **inspired** but it does not have `react-testing-library` as dependency, :( but `react-test-renderer` is so if we ever need to stay up to date we just update the library! 😄

**Comment by ellipticaldoor** [comment]
Oh I see, do you need some help to add this?

I can offer a hand if you point me on the right direction

**Comment by betoharres** [comment]
@ellipticaldoor Sorry I can't help you with this, I'm just a user of this library and short on time to solve this, but I was watching the issue testing-library/react-testing-library#281 and I think @threepointone could help us giving a good hint of what could be done.

**Comment by threepointone** [comment]
async act will be available on react-test-renderer too with the 16.9 release(it’s already in the alpha)

**Comment by threepointone** [comment]
Specifically, it’ll be Testrenderer.act

**Comment by betoharres** [comment]
@threepointone wow thanks for the quickly response! I'm happy we will see support for `async act` soon! 😃

**Comment by ellipticaldoor** [comment]
awesome!

**Comment by thymikee** [comment]
@oshimayoan is available in 1.9.1, enjoy!

**Comment by thymikee** [comment]
2.0 is out, go grab it! 🔥 
Blog post: https://callstack.com/blog/react-native-testing-library-2-0/
